/*
 * menus_id.h
 *
 *  Created on: Sep 29, 2015
 *      Author: arkadi
 */

#ifndef MENUS_ID_H_
#define MENUS_ID_H_

enum menu_id {
	MAIN_MENU_ID,
	AIRTOP_INFORMATION_MENU_ID,
	AIRTOP_CPU_MENU_ID,
	AIRTOP_GPU_MENU_ID,
	AIRTOP_HDD_MENU_ID,
	AIRTOP_DASHBOARD_MENU_ID,
	AIRTOP_SETTINGS_MENU_ID,
	NUMBER_OF_MENUS,
	AIRTOP_DEBUG_MENU_ID,
};

#endif /* MENUS_ID_H_ */
