/*
 * def.h
 *
 *  Created on: Oct 13, 2015
 *      Author: arkadi
 */

#ifndef DEF_H_
#define DEF_H_

enum information_type{
	SET_BRIGHTNESS,
	SET_SCREEN_SAVER_ENABLE,
	SET_SCREEN_SAVER_TIME,
	SET_SCREEN_SAVER_TYPE,
	SHOW_SERIAL_NUMBER,
	SHOW_PART_NUMBER,
	SHOW_MAC_ADDRESS,
	SHOW_POWER_STATE,
	SHOW_COMPUTER_POWER,
	SHOW_CPU_FREQUENCY,
	SHOW_HDD_SIZE,
	SHOW_MEMORY_SIZE,
	SHOW_HDD_TEMPERTURE,
	SHOW_CPU_TEMPERTURE,
	SHOW_GPU_TEMPERTURE,
	SHOW_AMBIENT_TEMPERATURE,
	SET_BOIS_STATE,
	SHOW_POST_CODE
};

enum frame_type {
	FRAME_REGULAR,
	FRAME_DASHBOARD,
};

enum action_type {
	ACTION_TYPE_NONE,
	ACTION_TYPE_SHOW_MENU,
	ACTION_TYPE_SHOW_DMI_MENU,
	ACTION_TYPE_SHOW_FRAME,
	ACTION_TYPE_SET_BIOS_STATE
};

enum power_state {
	POWER_OFF = 0x00,
	POWER_STD = 0x01,
	POWER_STR = 0x03,
	POWER_ON = 0x07,
};

enum display_state {
	DISPLAY_MENU,
	DISPLAY_FRAME,
	DISPLAY_ACTION_FRAME,
	DISPLAY_LOGO,
	DISPLAY_SLEEP,
};


#endif /* DEF_H_ */
