/*
 * layout.h
 *
 *  Created on: Sep 3, 2015
 *      Author: arkadi
 */

#ifndef LAYOUT_H_
#define LAYOUT_H_
#include "asf.h"

#define SIG_FIRST_BYTE_ADDRESS 		0X00
#define SIG_SECOND_BYTE_ADDRESS 	0X01
#define SIG_THIRD_BYTE_ADDRESS 		0X02
#define SIG_FOURTH_BYTE_ADDRESS 	0X03
#define LAYOUT_VERSION_ADDRESS 		0x04
#define MAJOR_REVISION_LSB_ADDRESS 	0x05
#define MAJOR_REVISION_MSB_ADDRESS 	0x06
#define MINOR_REVISION_LSB_ADDRESS 	0x07
#define MINOR_REVISION_MSB_ADDRESS 	0x08

#define POST_CODE_LSB_ADDRESS 		0x10
#define POST_CODE_MSB_ADDRESS 		0x11
#define POWER_STATE_ADDRESS 		0x12

#define CPU0_TEMP_ADDRESS 			0x20
#define CPU1_TEMP_ADDRESS 			0x21
#define CPU2_TEMP_ADDRESS 			0x22
#define CPU3_TEMP_ADDRESS 			0x23
#define CPU4_TEMP_ADDRESS 			0x24
#define CPU5_TEMP_ADDRESS 			0x25
#define CPU6_TEMP_ADDRESS 			0x26
#define CPU7_TEMP_ADDRESS 			0x27
#define GPU_TEMP_ADDRESS 			0x28
#define AMBIENT_TEMP_ADDRESS 		0x29
#define HARD_DISK0_TEMP_ADDRESS 	0x30
#define HARD_DISK1_TEMP_ADDRESS 	0x31
#define HARD_DISK2_TEMP_ADDRESS 	0x32
#define HARD_DISK3_TEMP_ADDRESS 	0x33
#define HARD_DISK4_TEMP_ADDRESS 	0x34
#define HARD_DISK5_TEMP_ADDRESS 	0x35
#define HARD_DISK6_TEMP_ADDRESS 	0x36
#define HARD_DISK7_TEMP_ADDRESS 	0x37
#define CPU_STATUS_ADDRESS 			0x38
#define TEMPERTURE_CONTROL_ADDRESS	0x39
#define HARD_DISK_STATUS_ADDRESS 	0x3a

#define ADC_LSB_ADDRESS 			0x40
#define ADC_MSB_ADDRESS 			0x41

#define MEM_SLOT01_ADDRESS 			0x50
#define MEM_SLOT23_ADDRESS 			0x51

#define HARD_DISK0_LSB_SZ_ADDRESS 	0x60
#define HARD_DISK0_MSB_SZ_ADDRESS 	0x61
#define HARD_DISK1_LSB_SZ_ADDRESS 	0x62
#define HARD_DISK1_MSB_SZ_ADDRESS 	0x63
#define HARD_DISK2_LSB_SZ_ADDRESS 	0x64
#define HARD_DISK2_MSB_SZ_ADDRESS 	0x65
#define HARD_DISK3_LSB_SZ_ADDRESS 	0x66
#define HARD_DISK3_MSB_SZ_ADDRESS 	0x67
#define HARD_DISK4_LSB_SZ_ADDRESS 	0x68
#define HARD_DISK4_MSB_SZ_ADDRESS 	0x69
#define HARD_DISK5_LSB_SZ_ADDRESS 	0x6a
#define HARD_DISK5_MSB_SZ_ADDRESS 	0x6b
#define HARD_DISK6_LSB_SZ_ADDRESS 	0x6c
#define HARD_DISK6_MSB_SZ_ADDRESS 	0x6d
#define HARD_DISK7_LSB_SZ_ADDRESS 	0x6e
#define HARD_DISK7_MSB_SZ_ADDRESS 	0x6f

#define CPU0F_LSB_ADDRESS 			0x70
#define CPU0F_MSB_ADDRESS 			0x71
#define CPU1F_LSB_ADDRESS 			0x72
#define CPU1F_MSB_ADDRESS 			0x73
#define CPU2F_LSB_ADDRESS 			0x74
#define CPU2F_MSB_ADDRESS 			0x75
#define CPU3F_LSB_ADDRESS 			0x76
#define CPU3F_MSB_ADDRESS 			0x77
#define CPU4F_LSB_ADDRESS 			0x78
#define CPU4F_MSB_ADDRESS 			0x79
#define CPU5F_LSB_ADDRESS 			0x7a
#define CPU5F_MSB_ADDRESS 			0x7b
#define CPU6F_LSB_ADDRESS 			0x7c
#define CPU6F_MSB_ADDRESS 			0x7d
#define CPU7F_LSB_ADDRESS 			0x7e
#define CPU7F_MSB_ADDRESS 			0x7f

#define RESET_ADDRESS 				0x80
#define REQUEST_ADDRESS 			0x81

#define DIRECT_TYPE_ADDRESS 		0x90
#define DIRECT_CONTENT_ADDRESS		0x91

#define RTC_TIME_ADDRESS 			0x98
#define RTC_DATE_ADDRESS			0x99


#define LAYOUT_VERSION_EEPROM_ADDRESS 		0x2c
#define SIG_FIRST_BYTE_EEPROM_ADDRESS 		0X2d
#define SIG_SECOND_BYTE_EEPROM_ADDRESS 		0X2e
#define SIG_THIRD_BYTE_EEPROM_ADDRESS 		0X2f
#define SIG_FOURTH_BYTE_EEPROM_ADDRESS 		0X30
#define MAJOR_REVISION_LSB_EEPROM_ADDRESS 	0x00
#define MAJOR_REVISION_MSB_EEPROM_ADDRESS 	0x01
#define MINOR_REVISION_LSB_EEPROM_ADDRESS 	0x02
#define MINOR_REVISION_MSB_EEPROM_ADDRESS 	0x03


#define BIOS_STATE_ADDRESS 0x18
#define SERIAL_NUMBER_ADDRESS 0x0c
#define PRODUCTION_YEAR_ADDRESS 0x0a
#define PRODUCTION_MONTH_ADDRESS 0x09
#define PRODUCTION_DAY_ADDRESS 0x08
#define MAC_ADDRESS 0x02
#define REVISION_ADDRESS 0x00


#define MAX_HARD_DISKS 	6
#define MAX_CPU			8
#define MAX_MEMORY_SLOT	4


struct direct_string_item {
	char *type;
	char *content;
	struct direct_string_item *next;
};

struct update_information {
	struct direct_string_item *direct_string;
	bool wen;
	bool valid_ambient;
	bool valid_gpu;
	bool req_cpu_temp;
	bool req_cpu_fq;
	bool req_gpu_temp;
	uint8_t gpu_temp;
	uint8_t ambient_temp;
	uint8_t mem_slot_sz[MAX_MEMORY_SLOT/2];
	uint8_t cpu_temp[MAX_CPU];
	uint8_t hd_temp[MAX_HARD_DISKS];
	uint16_t hd_size[MAX_HARD_DISKS];
	uint16_t cpu_fq[MAX_CPU];
	uint16_t bios_post_code;
};

struct update_information computer_data;

#endif /* LAYOUT_H_ */
