/*
 * eeprom_layout.h
 *
 * Created: 3/29/2017 5:23:59 PM
 *  Author: Nikita
 */


#ifndef EEPROM_LAYOUT_H_
#define EEPROM_LAYOUT_H_

#define MAC_ADDRESS_EEPROM_ADDRESS			0x04
#define MAC_ADDRESS_LENGTH 					6
#define SERIAL_NUMBER_EEPROM_ADDRESS 		0x14
#define SERIAL_NUMBER_LENGTH				12
#define LAYOUT_VERSION_EEPROM_ADDRESS 		0x2c
#define PRODUCT_NAME_EEPROM_ADDRESS			0x80
#define PRODUCT_NAME_LENGTH					16
#define PRODUCT_OPTIONS_EEPROM_ADDRESS		0x90
#define PRODUCT_OPTIONS_LENGTH				16
#define SCREEN_SAVER_TIME_EEPROM_ADDRESS	0x120
#define SCREEN_SAVER_CONFIG_EEPROM_ADDRESS	0x121
#define BRIGHTNESS_EEPROM_ADDRESS 			0x122

#define ASCII_FIELD_LENGTH					16

#endif /* EEPROM_LAYOUT_H_ */