#ifndef CONF_TWI_H_INCLUDED
#define CONF_TWI_H_INCLUDED

#define TWI_SLAVE_ADDRESS  		(0x30)
#define TWI_SLAVE_MSK		 	(0x03)
#define TWI_SLAVE_BASE        	(TWIE.SLAVE)
#define TWI_MASTER_BASE 	  	(TWIC.MASTER)

#endif /*CONF_TWI_H_INCLUDED*/
